f = open("readfile2.txt")
# print(f.tell())
# print(f.readline())
# print(f.tell())
# print(f.readline())
# print(f.tell())
# print(f.readline())
# print(f.tell())
# print(f.readline())
# print(f.tell())
print(f.readline())
f.seek(0)
print(f.readline())
f.seek(10)
print(f.readline())
f.close()

